Repository SatcherInstitute/health-equity-tracker, pull requests merged in 2022-03, with the labels that each got.

#1495 Fixes card offset and typo
  frontend/src/cards/MapCard.tsx
  frontend/src/cards/PopulationCard.tsx
  frontend/src/reports/TwoVariableReport.tsx
  frontend/src/reports/VariableDisparityReport.tsx
Labels: bug

#1497 Add refactor as option to template
  pull_request_template.md
Labels: documentation

#1507 Fix outstanding minor a11y issues
  frontend/src/cards/MapCard.tsx
  frontend/src/cards/ui/DropDownMenu.tsx
  frontend/src/cards/ui/MapBreadcrumbs.tsx
Labels: a11y, seo

#1502 Replaces No Data messages with "Insufficient Data"
  frontend/src/cards/MapCard.tsx
  frontend/src/cards/UnknownsMapCard.tsx
  frontend/src/cards/ui/MultiMapDialog.tsx
  frontend/src/charts/ChoroplethMap.tsx
  frontend/src/charts/Legend.tsx
  frontend/src/charts/TableChart.tsx
Labels: frontend

#1489 Sass Cleanup
  frontend/public/index.html
  frontend/src/App.module.scss
  frontend/src/Footer.module.scss
  frontend/src/cards/Card.module.scss
  frontend/src/cards/ui/MapBreadcrumbs.module.scss
  frontend/src/pages/AboutUs/AboutUsPage.module.scss
  frontend/src/pages/AboutUs/TheProjectTab.tsx
  frontend/src/pages/DataCatalog/DataCatalogPage.module.scss
  frontend/src/pages/DataCatalog/dataset_explorer/DataSourceListing.module.scss
  frontend/src/pages/DataCatalog/dataset_explorer/DatasetExplorer.module.scss
  frontend/src/pages/ExploreData/ExploreDataPage.module.scss
  frontend/src/pages/ExploreData/OptionsSelector.module.scss
  frontend/src/pages/Landing/LandingPage.module.scss
  frontend/src/pages/TermsOfUsePage/TermsOfUsePage.module.scss
  frontend/src/pages/WhatIsHealthEquity/EquityTab.tsx
  frontend/src/pages/WhatIsHealthEquity/FaqTab.tsx
  frontend/src/pages/WhatIsHealthEquity/News/News.module.scss
  frontend/src/pages/WhatIsHealthEquity/WhatIsHealthEquityPage.module.scss
  frontend/src/pages/ui/FaqSection.module.scss
  frontend/src/reports/Report.module.scss
  frontend/src/reports/ui/ShareButtons.module.scss
  frontend/src/styles/MaterialTheme.tsx
  frontend/src/styles/globals.scss
  frontend/src/styles/variables.module.scss
Labels: cleanup, frontend

#1179 Age adjustment race backend
  .github/linters/mypy.ini
  airflow/dags/cdc_restricted.py
  airflow/dags/census_pop_estimates.py
  config/data_sources/AGG_cdc_restricted.sql
  config/data_sources/census_pop_estimates.tf
  config/serviceaccounts.tf
  python/datasources/age_adjust_cdc_restricted.py
  python/datasources/cdc_restricted_local.py
  python/datasources/census_pop_estimates.py
  python/datasources/data_sources.py
  python/ingestion/constants.py
  python/ingestion/dataset_utils.py
  python/ingestion/gcs_to_bq_util.py
  python/ingestion/standardized_columns.py
  python/tests/data/age_adjustment/age_adjusted.json
  python/tests/data/age_adjustment/cdc_restricted-by_race_national-with_age_adjust.json
  python/tests/data/age_adjustment/cdc_restricted-by_race_state-with_age_adjust.json
  python/tests/data/age_adjustment/cdc_restricted-race_age_state.json
  python/tests/data/age_adjustment/cdc_restricted_race_state.json
  python/tests/data/age_adjustment/census_pop_estimates.csv
  python/tests/data/age_adjustment/expected_deaths.json
  python/tests/data/age_adjustment/race_age_state_simple.json
  python/tests/data/cdc_restricted_local/COVID_Cases_Restricted_Detailed_04302021_Part_1.csv
  python/tests/data/cdc_restricted_local/COVID_Cases_Restricted_Detailed_04302021_Part_2.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_age_county.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_age_state.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_and_age_national.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_and_age_state.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_county.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_state.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_sex_county.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_sex_state.csv
  python/tests/data/census_pop_estimates/census_pop_estimates-race_ethnicity_age_national.csv
  python/tests/data/census_pop_estimates/census_pop_estimates-race_ethnicity_age_state.csv
  python/tests/data/census_pop_estimates/census_pop_estimates.csv
  python/tests/datasources/test_acs_population.py
  python/tests/datasources/test_age_adjustment.py
  python/tests/datasources/test_cdc_restricted_local.py
  python/tests/datasources/test_census_pop_estimates.py
  python/tests/ingestion/test_dataset_utils.py
Labels: Data

#1510 Better Naming
  frontend/src/cards/DisparityBarChartCard.tsx
  frontend/src/cards/MapCard.tsx
  frontend/src/cards/ui/MultiMapDialog.tsx
  frontend/src/cards/ui/UnknownsAlert.tsx
  frontend/src/charts/ChoroplethMap.tsx
  frontend/src/charts/DisparityBarChart.tsx
  frontend/src/charts/SimpleHorizontalBarChart.tsx
  frontend/src/charts/TableChart.tsx
  frontend/src/data/config/MetricConfig.ts
  frontend/src/reports/OneVariableReport.tsx
  frontend/src/reports/ReportProvider.tsx
  frontend/src/reports/storybook/VariableReport.stories.tsx
Labels: cleanup

#1514 Use Unique VariableIds
  frontend/src/cards/DisparityBarChartCard.tsx
  frontend/src/cards/MapCard.tsx
  frontend/src/cards/TableCard.tsx
  frontend/src/data/config/MetricConfig.ts
  frontend/src/data/utils/datasetutils.ts
  frontend/src/pages/ExploreData/ExploreDataPage.tsx
Labels: cleanup

#1504 Scroll to Specific Highlighted Card from External #HashLink
  frontend/src/pages/ExploreData/ExploreDataPage.tsx
  frontend/src/reports/OneVariableReport.tsx
  frontend/src/reports/Report.module.scss
  frontend/src/reports/ReportProvider.tsx
  frontend/src/utils/urlutils.tsx
Labels: feature request

#1530 Intercept old datatype params
  frontend/src/reports/OneVariableReport.tsx
  frontend/src/reports/TwoVariableReport.tsx
  frontend/src/utils/urlutils.tsx
Labels: bug

#1521 Load ACS2010 from /data
  python/datasources/acs_2010_population.py
  python/datasources/acs_health_insurance.py
  python/datasources/acs_household_income.py
  python/datasources/acs_population.py
  python/datasources/acs_poverty.py
  python/datasources/age_adjust_cdc_restricted.py
  python/datasources/cdc_restricted.py
  python/datasources/cdc_vaccination_county.py
  python/datasources/cdc_vaccination_national.py
  python/datasources/census_pop_estimates.py
  python/datasources/county_adjacency.py
  python/datasources/county_names.py
  python/datasources/covid_tracking_project.py
  python/datasources/covid_tracking_project_metadata.py
  python/datasources/data_source.py
  python/datasources/household_income.py
  python/datasources/kff_vaccination.py
  python/datasources/manual_uploads.py
  python/datasources/primary_care_access.py
  python/datasources/state_names.py
  python/datasources/uhc.py
  python/ingestion/gcs_to_bq_util.py
  python/tests/datasources/test_acs_population.py
  python/tests/datasources/test_age_adjustment.py
  python/tests/datasources/test_cdc_vaccination_county.py
  python/tests/datasources/test_cdc_vaccination_national.py
  python/tests/datasources/test_census_pop_estimates.py
  python/tests/datasources/test_covid_tracking_project.py
  python/tests/datasources/test_covid_tracking_project_metadata.py
  python/tests/datasources/test_kff_vaccination.py
  python/tests/datasources/test_uhc_brfss.py
  python/tests/ingestion/test_dataset_utils.py
  python/tests/test_census.py
  python/tests/test_gcs_to_bq.py
  run_gcs_to_bq/Dockerfile
Labels: cleanup, Data
