Repository SatcherInstitute/health-equity-tracker, pull requests merged in 2023-09, with the labels that each got.

#2346 Backend: Remove covid suppression
  python/datasources/cdc_restricted.py
  python/datasources/cdc_restricted_local.py
  python/tests/data/cdc_restricted/golden_data/by_sex_national_cumulative.json
  python/tests/data/cdc_restricted/golden_data/by_sex_national_time_series.json
  python/tests/data/cdc_restricted/golden_data/by_sex_state_cumulative.json
  python/tests/data/cdc_restricted/golden_data/by_sex_state_time_series.json
  python/tests/data/cdc_restricted_local/cdc_restricted_by_age_county.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_age_state.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_and_age_national.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_and_age_state.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_county.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_race_state.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_sex_county.csv
  python/tests/data/cdc_restricted_local/cdc_restricted_by_sex_state.csv
Labels: cleanup, Data

#2360 Make optional metric configs: `pct_share` and `pct_share_unknown`
  frontend/src/cards/DisparityBarChartCard.tsx
  frontend/src/cards/RateTrendsChartCard.tsx
  frontend/src/cards/ShareTrendsChartCard.tsx
  frontend/src/cards/UnknownsMapCard.tsx
  frontend/src/cards/ui/AltTableView.tsx
  frontend/src/data/config/MetricConfig.ts
  frontend/src/data/config/MetricConfigPhrma.ts
  frontend/src/data/utils/DatasetTimeUtils.test.ts
  frontend/src/data/utils/DatasetTimeUtils.ts
  frontend/src/data/utils/datasetutils.test.ts
  frontend/src/data/utils/datasetutils.ts
  frontend/src/reports/Report.tsx
Labels: feature request, cleanup

#2366 update readme
  README.md
  frontend/package-lock.json
Labels: documentation

#2367 BACKEND: `remove_non_current_` fn and BQ DTYPES
  python/ingestion/dataset_utils.py
  python/ingestion/gcs_to_bq_util.py
  python/tests/datasources/test_geo_context.py
  python/tests/ingestion/test_dataset_utils.py
  python/tests/ingestion/test_gcs_to_bq.py
Labels: Performance Optimization, backend-calculations

#2371 Adjust Super Linter Settings
  .github/linters/black.ini
  .github/workflows/runMyPy.yml
  .github/workflows/runSuperLinter.yml
  pyproject.toml
Labels: DX

#2362 BACKEND: Split hiv into `_historical` and `_current`
  .github/workflows/runSuperLinter.yml
  README.md
  airflow/dags/cdc_hiv.py
  cspell.config.json
  data/cdc_hiv/hiv_stigma_index/hiv_stigma_index-national-race_and_ethnicity.csv
  python/datasources/age_adjust_cdc_hiv.py
  python/datasources/cdc_hiv.py
  python/ingestion/constants.py
  python/tests/data/cdc_hiv/golden_data/age_national_current.csv
  python/tests/data/cdc_hiv/golden_data/age_national_historical.csv
  python/tests/data/cdc_hiv/golden_data/age_national_time_series.csv
  python/tests/data/cdc_hiv/golden_data/race_and_ethnicity_national_current.csv
  python/tests/data/cdc_hiv/golden_data/race_and_ethnicity_national_historical.csv
  python/tests/data/cdc_hiv/golden_data/race_and_ethnicity_national_time_series.csv
  python/tests/data/cdc_hiv/golden_data/sex_county_current.csv
  python/tests/data/cdc_hiv/golden_data/sex_county_historical.csv
  python/tests/data/cdc_hiv/golden_data/sex_county_time_series.csv
  python/tests/data/cdc_hiv/golden_data/sex_state_current.csv
  python/tests/data/cdc_hiv/golden_data/sex_state_historical.csv
  python/tests/data/cdc_hiv/golden_data/sex_state_time_series.csv
  python/tests/data/cdc_hiv/hiv_stigma_index/hiv_stigma_index-national-age.csv
  python/tests/data/cdc_hiv/hiv_stigma_index/hiv_stigma_index-national-all.csv
  python/tests/data/cdc_hiv/hiv_stigma_index/hiv_stigma_index-national-race_and_ethnicity.csv
  python/tests/data/cdc_hiv/hiv_stigma_index/hiv_stigma_index-national-sex.csv
  python/tests/data/cdc_hiv/hiv_stigma_index/hiv_stigma_index-state-all.csv
  python/tests/data/cdc_hiv_age_adjustment/golden_data/race_and_ethnicity_national_current-with_age_adjust.csv
  python/tests/data/cdc_hiv_age_adjustment/golden_data/race_and_ethnicity_national_time_series-with_age_adjust.csv
  python/tests/data/cdc_hiv_age_adjustment/golden_data/race_and_ethnicity_state_current-with_age_adjust.csv
  python/tests/data/cdc_hiv_age_adjustment/golden_data/race_and_ethnicity_state_time_series-with_age_adjust.csv
  python/tests/data/cdc_hiv_age_adjustment/race_and_ethnicity_national_current.csv
  python/tests/data/cdc_hiv_age_adjustment/race_and_ethnicity_national_time_series.csv
  python/tests/data/cdc_hiv_age_adjustment/race_and_ethnicity_state_current.csv
  python/tests/data/cdc_hiv_age_adjustment/race_and_ethnicity_state_time_series.csv
  python/tests/data/cdc_hiv_black_women/golden_data/black_women_national_current.csv
  python/tests/data/cdc_hiv_black_women/golden_data/black_women_national_historical.csv
  python/tests/data/cdc_hiv_black_women/golden_data/black_women_national_time_series.csv
  python/tests/datasources/test_age_adjustment_cdc_hiv.py
  python/tests/datasources/test_cdc_hiv.py
  race_and_ethnicity_national_current-with_age_adjust.csv
  race_and_ethnicity_state_current-with_age_adjust.csv
Labels: Data

#2384 Frontend: Update HIV to fetch newly split `_current` and `_historical` files
  frontend/playwright.config.ts
  frontend/src/data/config/DatasetMetadata.ts
  frontend/src/data/config/MetadataMap.ts
  frontend/src/data/providers/HivProvider.test.ts
  frontend/src/data/providers/HivProvider.ts
Labels: frontend, Performance Optimization

#2383 Adds SubPopulation Breadcrumb
  frontend/src/cards/MapCard.tsx
  frontend/src/cards/ui/GeoContext.test.ts
  frontend/src/cards/ui/GeoContext.tsx
  frontend/src/cards/ui/MapBreadcrumbs.tsx
  frontend/src/cards/ui/MultiMapDialog.tsx
  frontend/src/data/config/MetricConfig.ts
  frontend/src/data/config/MetricConfigPhrma.ts
Labels: feature request

#2387 FRONTEND: Update metadata for covid sept 2023
  frontend/src/data/config/DatasetMetadata.ts
Labels: Data

#2400 Lazy iframes
  frontend/index.html
  frontend/src/pages/ExploreData/DefaultHelperBox.tsx
  frontend/src/pages/ExploreData/OnboardingSteps.tsx
  frontend/src/pages/Landing/LandingPage.tsx
  frontend/src/pages/WhatIsHealthEquity/EquityTab.tsx
Labels: Performance Optimization
